services:
  mariadb:
    container_name: mariadb
    environment:
     - DB_NAME=${DB_NAME}
     - DB_USER=${DB_USER}
     - DB_PASSWORD=${DB_PASSWORD}
     - DB_ROOTPASSWORD=${DB_ROOTPASSWORD}
    build: ./requirements/mariadb
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p${DB_ROOTPASSWORD} > /dev/null 2>&1"]
      interval: 5s
      retries: 10
      start_period: 10s
    networks: 
      - inception
    volumes:
      - database:/var/lib/mysql:rw

  nginx:
    container_name: nginx
    environment:
      - URL=${URL}
      - BONUS_URL=${BONUS_URL}
    build: ./requirements/nginx
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/wp-login.php || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - inception
    volumes:
      - web:/var/www/html:rw
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_healthy
      uptime-kuma:
        condition: service_healthy
      website:
        condition: service_healthy

  wordpress:
    container_name: wordpress
    environment:
      - URL=${URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - WP_ADMIN=${WP_ADMIN}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
    build: ./requirements/wordpress
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "cgi-fcgi -bind -connect localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - inception
    volumes:
      - web:/var/www/html:rw
    depends_on:
      mariadb:
        condition: service_healthy
    
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG || exit 1" ]
      interval: 5s
      retries: 10
    networks:
      - inception

  ftp:
    container_name: ftp
    environment:
     - FTP_USER=${FTP_USER}
     - FTP_PASSWORD=${FTP_PASSWORD}
    build: ./requirements/bonus/ftp
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 21 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - inception
    volumes:
      - web:/home/ftp:ro
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    depends_on:
      wordpress:
        condition: service_healthy

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"] 
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy

  uptime-kuma:
    container_name: uptime-kuma
    build: ./requirements/bonus/uptime-kuma
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - inception
    volumes:
      - kuma:/uptime-kuma/data

  website:
    container_name: website
    build: ./requirements/bonus/website
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -fk http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - inception
    volumes:
      - "./requirements/bonus/website/tools:/var/www/html"

networks:
  inception:

volumes:
  database:
    driver_opts:
      type: 'none'
      o: bind
      device: ${DATA}/database
  web:
    driver_opts:
      type: 'none'
      o: bind
      device: ${DATA}/web
  kuma:
    driver_opts:
      type: 'none'
      o: bind
      device: ${DATA}/kuma