services:
  mariadb:
    container_name: mariadb
    env_file: .env
    build: ./requirements/mariadb
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -u root > /dev/null 2>&1" ]
      interval: 5s
      retries: 10
    networks: 
      - inception
    volumes:
      - ./data/database:/var/lib/mysql:rw

  nginx:
    container_name: nginx
    env_file: .env
    build: ./requirements/nginx
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pgrep nginx || exit 1"]
      interval: 5s
      retries: 10
    networks:
      - inception
    volumes:
      - ./data/web:/var/www/html:rw
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    container_name: wordpress
    env_file: .env
    build: ./requirements/wordpress
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep php-fpm || exit 1" ]
      interval: 5s
      retries: 10
    networks:
      - inception
    volumes:
      - ./data/web:/var/www/html:rw
    depends_on:
      mariadb:
        condition: service_healthy
    
  redis:
    container_name: redis
    env_file: .env
    build: ./requirements/bonus/redis
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG || exit 1" ]
      interval: 5s
      retries: 10
    networks:
      - inception

  ftp:
    container_name: ftp
    env_file: .env
    build: ./requirements/bonus/ftp
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep vsftpd || exit 1" ]
      interval: 5s
      retries: 10
    networks:
      - inception
    volumes:
      - ./data/web:/home/ftp:ro
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    depends_on:
      wordpress:
        condition: service_healthy

  adminer:
    container_name: adminer
    env_file: .env
    build: ./requirements/bonus/adminer
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pgrep php || exit 1" ]
      interval: 5s
      retries: 10
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy

  uptime-kuma:
    container_name: uptime-kuma
    env_file: .env
    build: ./requirements/bonus/uptime-kuma
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/ || exit 1" ]
      interval: 5s
      retries: 10
    networks:
      - inception
    volumes:
      - ./data/uptime-kuma-data:/uptime-kuma/data
    ports:
      - "3000:3000"
    depends_on:
      mariadb:
        condition: service_healthy
      adminer:
        condition: service_healthy
      ftp:
        condition: service_healthy
      redis:
        condition: service_healthy
      wordpress:
        condition: service_healthy
      nginx:
        condition: service_healthy


networks:
  inception: